name: on_push

on:
  push:
    branches:
      - "**" # This will run on all branches, and must be quoted to be handled by yaml

jobs:

  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Set start time
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Run tests with maven
        run: mvn test
      - name: Collect build data
        if: always()
        run: |
          echo "Total_Duration=$(expr $(date +%s) - ${START_TIME})"
          username=$(pwd)
          echo "The current user is: $username"
          /home/runner/work/Observability/Observability/Resources/moreData.sh

          
